services:
  prices-api:
    build:
      context: ./prices-api
      dockerfile: ./Dockerfile
    environment:    
      - POSTGRES_HOST=${DB_HOST}      
      - POSTGRES_DB=${DB_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_PORT=5432
      - PRICES_URL=${PRICES_URL}
      - PRICES_PASS=${PRICES_PASS}
    ports:
      - "8080:8080"
    depends_on:
      - pg
  users-api:
    build:
      context: ./users-api
      dockerfile: ./Dockerfile
    environment:    
      - POSTGRES_HOST=${DB_HOST}      
      - POSTGRES_DB=${DB_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_PORT=5432
      - ADMIN_PASS=${ADMIN_PASS}
      - USER_PASS=${USER_PASS}
    ports:
      - "8081:8081"
    depends_on:
      - pg
  ui:
    build:
      context: ./ui
      args:
          ENV: preprod
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    links:
      - prices-api
      - users-api
    depends_on:
      - prices-api
      - users-api
  pg:
    image: "postgres:9.6-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=${DB_HOST}      
      - POSTGRES_DB=${DB_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
       - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: