services:
  prices-api:
    build:
      context: ./prices-api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8080"
  users-api:
    build:
      context: ./users-api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8081:8081"
  ui:
    build:
      context: ./ui
      dockerfile: ./Dockerfile.dev
    ports:
      - "80:80"
    links:
      - prices-api
      - users-api
    depends_on:
      - prices-api
      - users-api