FROM maven:3.8.5-openjdk-17-slim AS BUILD_STAGE
RUN mkdir -p /workspace
WORKDIR /workspace
COPY pom.xml /workspace
COPY src /workspace/src
RUN mvn -B -f pom.xml clean package -DskipTests

FROM openjdk:17-jdk-slim
COPY --from=BUILD_STAGE /workspace/target/users-api*.jar users-api.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","users-api.jar"]