name: deploy-develop
on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  deploy_preproduction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Okteto CLI
        run: curl https://get.okteto.com -sSfL | sh
          
      - name: Okteto login
        run: okteto context --token ${{ secrets.OKTETO_TOKEN }} use
        
      - name: Go to namespace
        run: okteto namespace --personal tfg-preprod-sergiocarrascosasanchez
        
      - name: Deploy
        run: okteto deploy --file docker-compose.preprod.yaml --wait --build