name: deploy-develop
on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name:  Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Run prices-api tests
        run: |
              cd ./prices-api
              mvn test
      - name: Run users-api tests
        run: |
              cd ./users-api
              mvn test
      - name: Set up Node 16.15.1
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - name: Run ui tests
        run: |
              cd ./ui
              npm i
              npm run test-ci

      - name: Get Okteto CLI
        run: curl https://get.okteto.com -sSfL | sh
          
      - name: Okteto login
        run: okteto context --token ${{ secrets.OKTETO_TOKEN }} use
        
      - name: Go to namespace
        run: okteto namespace --personal tfg-preprod-sergiocarrascosasanchez
        
      - name: Deploy
        run: okteto deploy --file docker-compose.preprod.yaml --wait --build